-- 0084 — Import bibliothèque calisthénie (PR2) — exercices, progressions, guide
-- Idempotent (garde par ref / key / slug). Généré depuis datasets/calisthenie_complet.json

insert into public.exercise_library (ref,name,name_en,category,body_part,muscle_group,target_muscle,secondary_muscles,equipment,no_equipment,level,measure,exercise_type,unilateral,is_calisthenics,source,attribution)
select v.ref,v.name,v.name_en,v.category,v.category,v.muscle_group,v.target_muscle,v.secondary_muscles,v.equipment,v.no_equipment,v.level,v.measure,v.exercise_type,v.unilateral,v.is_calisthenics,v.source,v.attribution from (values
('cal:1','Tractions pronation','Pull-ups','pull','pull','dos','["dos", "biceps"]'::jsonb,'barre_traction',false,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:2','Tractions supination','Chin-ups','pull','pull','dos','["dos", "biceps"]'::jsonb,'barre_traction',false,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:3','Tractions archer','Archer Pull-ups','pull','pull','dos','["dos", "biceps"]'::jsonb,'barre_traction',false,'avance','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:4','Tractions négatives','Negative Pull-ups','pull','pull','dos','["dos", "biceps"]'::jsonb,'barre_traction',false,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:5','L Pull-up','L Pull-up','pull','pull','dos','["dos", "biceps", "abdos"]'::jsonb,'barre_traction',false,'avance','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:6','Rowing australien','Inverted Rows','pull','pull','dos','["dos", "biceps"]'::jsonb,'barre_traction',false,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:7','Rowing aux anneaux','Ring Rows','pull','pull','dos','["dos", "biceps"]'::jsonb,'anneaux',false,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:8','Renegade row','Renegade Rows','pull','pull','dos','["dos", "abdos", "epaules"]'::jsonb,'aucun',true,'intermediaire','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:9','Superman pull','Superman Pull','pull','pull','dos','["dos", "lombaires"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:10','Front lever groupé','Tuck Front Lever','pull','pull','dos','["dos", "abdos"]'::jsonb,'barre_traction',false,'intermediaire','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:11','Skin the cat','Skin The Cat','pull','pull','dos','["dos", "epaules"]'::jsonb,'anneaux',false,'avance','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:12','Curl au poids du corps','Bodyweight Curls','pull','pull','biceps','["biceps"]'::jsonb,'barre_traction',false,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:13','Haussements d''épaules suspendu','Hanging Scapula Shrugs','pull','pull','trapezes','["trapezes", "dos"]'::jsonb,'barre_traction',false,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:14','Élévations IYT au sol','Lying IYT Raises','pull','pull','epaules','["epaules", "dos"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:15','Soulevé de terre au poids du corps','Bodyweight Deadlift','pull','pull','ischios','["ischios", "fessiers", "lombaires"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:16','Pompes','Push-ups','push','push','pectoraux','["pectoraux", "triceps", "epaules"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:17','Pompes déclinées','Decline Push-ups','push','push','pectoraux','["pectoraux", "epaules"]'::jsonb,'chaise_banc',false,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:18','Pompes diamant','Diamond Push-ups','push','push','triceps','["triceps", "pectoraux"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:19','Pompes prise serrée','Close Grip Push-ups','push','push','triceps','["triceps", "pectoraux"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:20','Pompes archer','Archer Push-ups','push','push','pectoraux','["pectoraux", "triceps"]'::jsonb,'aucun',true,'intermediaire','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:21','Pompes archer australiennes','Archer Australian Push-ups','push','push','dos','["dos", "pectoraux"]'::jsonb,'barre_traction',false,'avance','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:22','Pompes piquées','Pike Push-ups','push','push','epaules','["epaules", "triceps"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:23','Pompes dive bomber','Dive Bomber Push-ups','push','push','epaules','["epaules", "pectoraux", "triceps"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:24','Pompes décalées','Staggered Push-ups','push','push','pectoraux','["pectoraux", "triceps"]'::jsonb,'aucun',true,'intermediaire','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:25','Pompes négatives','Negative Push-ups','push','push','pectoraux','["pectoraux", "triceps"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:26','Pompes pseudo planche','Pseudo Planche Push-ups','push','push','epaules','["epaules", "pectoraux"]'::jsonb,'aucun',true,'avance','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:27','HSPU au mur','Wall Handstand Push-ups','push','push','epaules','["epaules", "triceps"]'::jsonb,'mur',false,'avance','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:28','Dips aux barres','Bar Dips','push','push','pectoraux','["pectoraux", "triceps", "epaules"]'::jsonb,'barres_paralleles',false,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:29','Dips aux anneaux','Ring Dips','push','push','pectoraux','["pectoraux", "triceps"]'::jsonb,'anneaux',false,'avance','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:30','Dips sur chaise / banc','Bench / Chair Dips','push','push','triceps','["triceps", "epaules"]'::jsonb,'chaise_banc',false,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:31','Dips au sol','Floor Dips','push','push','triceps','["triceps"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:32','Extension triceps au poids du corps','Bodyweight Triceps Extension','push','push','triceps','["triceps"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:33','Extension triceps en planche','Plank Triceps Extension','push','push','triceps','["triceps", "abdos"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:34','Push press au poids du corps','Push Press','push','push','epaules','["epaules", "triceps"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:35','Élévations latérales au poids du corps','Bodyweight Lateral Raises','push','push','epaules','["epaules"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:36','Squats','Squats','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:37','Squats latéraux','Side / Lateral Squats','jambes','jambes','quadriceps','["quadriceps", "adducteurs", "fessiers"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:38','Squats archer','Archer Squats','jambes','jambes','quadriceps','["quadriceps", "adducteurs"]'::jsonb,'aucun',true,'intermediaire','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:39','Pistol squats','Pistol Squats','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'aucun',true,'avance','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:40','Squats bulgares','Bulgarian Split Squats','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'chaise_banc',false,'intermediaire','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:41','Split squats','Split Squats','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:42','Sissy squats','Sissy Squats','jambes','jambes','quadriceps','["quadriceps"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:43','Squats plié','Plie Squats','jambes','jambes','adducteurs','["adducteurs", "quadriceps"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:44','Squats sumo','Sumo Squats','jambes','jambes','adducteurs','["adducteurs", "fessiers"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:45','Pop squats','Pop Squats','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:46','Squats sautés','Squat Jumps','jambes','jambes','quadriceps','["quadriceps", "fessiers", "mollets"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:47','Fentes croisées (curtsy)','Curtsy Lunges','jambes','jambes','fessiers','["fessiers", "quadriceps"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:48','Fentes arrière','Reverse Lunges','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:49','Fentes latérales','Lateral Lunges','jambes','jambes','adducteurs','["adducteurs", "quadriceps"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:50','Fentes sautées','Jumping Lunges','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'aucun',true,'intermediaire','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:51','Kickbacks fessiers','Glute Kickbacks','jambes','jambes','fessiers','["fessiers"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:52','Pont fessier','Glute Bridge','jambes','jambes','fessiers','["fessiers", "ischios"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:53','Pont fessier unilatéral','Single-leg Bridge','jambes','jambes','fessiers','["fessiers", "ischios"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:54','Frog pumps','Frog Pumps','jambes','jambes','fessiers','["fessiers"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:55','Soulevé de terre unilatéral','Single-Leg Deadlift','jambes','jambes','ischios','["ischios", "fessiers"]'::jsonb,'aucun',true,'intermediaire','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:56','Extensions mollets','Calf Raises','jambes','jambes','mollets','["mollets"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:57','Donkey calf raises','Donkey Calf Raises','jambes','jambes','mollets','["mollets"]'::jsonb,'chaise_banc',false,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:58','Chaise au mur sur pointes','Tip Toe Wall Sit','jambes','jambes','quadriceps','["quadriceps", "mollets"]'::jsonb,'mur',false,'intermediaire','temps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:59','Chaise au mur talons levés','Heel Raised Wall Sit','jambes','jambes','quadriceps','["quadriceps"]'::jsonb,'mur',false,'intermediaire','temps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:60','Crunchs','Crunches','core','core','abdos','["abdos"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:61','Crunchs inversés','Reverse Crunches','core','core','abdos','["abdos"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:62','Hollow body crunch','Hollow Body Crunch','core','core','abdos','["abdos"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:63','Crunchs bicyclette','Bicycle Crunches','core','core','abdos','["abdos", "obliques"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:64','Dead bug','Dead Bug Crunch','core','core','abdos','["abdos"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:65','Relevés de buste','Sit-ups','core','core','abdos','["abdos"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:66','V-ups','V Ups','core','core','abdos','["abdos"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:67','V-up hold','V-Up Hold','core','core','abdos','["abdos"]'::jsonb,'aucun',true,'intermediaire','temps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:68','Tuck-up unilatéral','Single-Leg Tuck-up','core','core','abdos','["abdos"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:69','Relevés de jambes suspendu','Hanging Leg Raises','core','core','abdos','["abdos", "flechisseurs_hanche"]'::jsonb,'barre_traction',false,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:70','Relevés de genoux suspendu','Hanging Knee Raises','core','core','abdos','["abdos"]'::jsonb,'barre_traction',false,'debutant','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:71','Genoux aux coudes suspendu','Hanging Knees to Elbows','core','core','abdos','["abdos"]'::jsonb,'barre_traction',false,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:72','Toes to bar','Toes to Bar','core','core','abdos','["abdos"]'::jsonb,'barre_traction',false,'avance','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:73','L-sit','L-Sit','core','core','abdos','["abdos", "quadriceps"]'::jsonb,'barres_paralleles',false,'avance','temps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:74','Dragon flag','Dragon Flag','core','core','abdos','["abdos"]'::jsonb,'chaise_banc',false,'avance','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:75','Essuie-glaces','Windshield Wipers','core','core','obliques','["obliques", "abdos"]'::jsonb,'aucun',true,'intermediaire','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:76','Russian twist','Russian Twist','core','core','obliques','["obliques"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:77','Talons alternés','Alternating Heel Taps','core','core','obliques','["obliques"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:78','Battements de jambes','Flutter Kicks','core','core','abdos','["abdos"]'::jsonb,'aucun',true,'debutant','temps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:79','Gainage ventral','Plank','core','core','abdos','["abdos", "lombaires"]'::jsonb,'aucun',true,'debutant','temps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:80','Gainage latéral','Side Plank','core','core','obliques','["obliques"]'::jsonb,'aucun',true,'debutant','temps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:81','Rotations de hanche en gainage latéral','Side Plank Hip Dips','core','core','obliques','["obliques"]'::jsonb,'aucun',true,'intermediaire','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:82','Touches d''épaules en planche','Shoulder Taps','core','core','abdos','["abdos", "epaules"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:83','Touches de genoux en planche haute','High Plank Knee Taps','core','core','abdos','["abdos"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:84','Spider plank crunch','Spider Plank Crunch','core','core','obliques','["obliques", "abdos"]'::jsonb,'aucun',true,'intermediaire','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:85','Bird dog plank','Bird Dog Plank','core','core','lombaires','["lombaires", "abdos", "fessiers"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:86','Roue abdominale','Ab Wheel Rollout','core','core','abdos','["abdos", "dos"]'::jsonb,'roue_abdominale',false,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:87','Jumping jacks','Jumping Jacks','cardio','cardio','corps_entier','["corps_entier"]'::jsonb,'aucun',true,'debutant','temps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:88','Burpees','Burpees','cardio','cardio','corps_entier','["corps_entier"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:89','Mountain climbers','Mountain Climbers','cardio','cardio','abdos','["abdos", "corps_entier"]'::jsonb,'aucun',true,'debutant','temps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:90','Mountain climbers croisés','Crossbody Mountain Climbers','cardio','cardio','obliques','["obliques", "abdos"]'::jsonb,'aucun',true,'intermediaire','temps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:91','Montées de genoux','High Knee Runs','cardio','cardio','quadriceps','["quadriceps", "mollets"]'::jsonb,'aucun',true,'debutant','temps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:92','Touches genoux hauts','High Knee Taps','cardio','cardio','quadriceps','["quadriceps", "abdos"]'::jsonb,'aucun',true,'debutant','temps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:93','Talons-fesses','Butt Kicks','cardio','cardio','ischios','["ischios", "mollets"]'::jsonb,'aucun',true,'debutant','temps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:94','Shadow boxing','Shadow Punches','cardio','cardio','epaules','["epaules", "corps_entier"]'::jsonb,'aucun',true,'debutant','temps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:95','Équilibre sur les mains contre le mur','Supported Handstand Hold','equilibre','equilibre','epaules','["epaules", "abdos"]'::jsonb,'mur',false,'intermediaire','temps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:96','Gainage latéral statique','Side Plank Hold','equilibre','equilibre','obliques','["obliques"]'::jsonb,'aucun',true,'debutant','temps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:97','Posture du corbeau','Crane Pose','equilibre','equilibre','epaules','["epaules", "abdos", "avant_bras"]'::jsonb,'aucun',true,'avance','temps','basique',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:98','Bird dog','Bird Dog','equilibre','equilibre','lombaires','["lombaires", "abdos"]'::jsonb,'aucun',true,'debutant','temps','basique',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:99','Étirement du pigeon','Pigeon Pose / Stretch','mobilite','mobilite','hanches','["hanches", "fessiers"]'::jsonb,'aucun',true,'debutant','temps','mobilite',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:100','Chien tête en bas','Downward Facing Dog','mobilite','mobilite','ischios','["ischios", "mollets", "epaules"]'::jsonb,'aucun',true,'debutant','temps','mobilite',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:101','Chien tête en haut','Upward Facing Dog','mobilite','mobilite','abdos','["abdos", "pectoraux", "lombaires"]'::jsonb,'aucun',true,'debutant','temps','mobilite',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:102','Posture du dauphin','Dolphin Pose','mobilite','mobilite','epaules','["epaules", "ischios"]'::jsonb,'aucun',true,'debutant','temps','mobilite',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:103','Étirement papillon','Butterfly Stretch','mobilite','mobilite','adducteurs','["adducteurs", "hanches"]'::jsonb,'aucun',true,'debutant','temps','mobilite',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:104','Flexion avant debout','Forward Fold','mobilite','mobilite','ischios','["ischios", "lombaires"]'::jsonb,'aucun',true,'debutant','temps','mobilite',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:105','Posture du chameau','Camel Pose','mobilite','mobilite','quadriceps','["quadriceps", "abdos", "pectoraux"]'::jsonb,'aucun',true,'intermediaire','temps','mobilite',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:106','Posture de l''enfant','Child''s Pose','mobilite','mobilite','dos','["dos", "hanches"]'::jsonb,'aucun',true,'debutant','temps','mobilite',false,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:107','Torsion vertébrale allongée','Supine Spinal Twist','mobilite','mobilite','dos','["dos", "obliques"]'::jsonb,'aucun',true,'debutant','temps','mobilite',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:108','Essuie-glaces allongés (mobilité)','Lying Windshield Wiper','mobilite','mobilite','hanches','["hanches", "obliques"]'::jsonb,'aucun',true,'debutant','temps','mobilite',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:109','World''s greatest stretch','World''s Greatest Stretch','mobilite','mobilite','hanches','["hanches", "dos", "ischios"]'::jsonb,'aucun',true,'debutant','temps','mobilite',true,true,'thefitnessphantom_12w','Calisthénie — source : https://thefitnessphantom.com/12-week-calisthenics-program-with-pdf'),
('cal:110','Frog stand','Frog Stand','skill','skill','epaules','["epaules", "abdos", "avant_bras"]'::jsonb,'aucun',true,'debutant','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:111','ATR dos au mur','Wall Handstand (back to wall)','skill','skill','epaules','["epaules", "abdos"]'::jsonb,'mur',false,'debutant','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:112','ATR ventre au mur','Reverse Wall Handstand','skill','skill','epaules','["epaules", "abdos"]'::jsonb,'mur',false,'intermediaire','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:113','ATR libre','Freestanding Handstand','skill','skill','epaules','["epaules", "abdos"]'::jsonb,'aucun',true,'avance','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:114','L-sit to handstand','L-sit to Handstand','skill','skill','epaules','["epaules", "abdos"]'::jsonb,'barres_paralleles',false,'avance','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:115','Press to handstand','Press to Handstand','skill','skill','epaules','["epaules", "abdos"]'::jsonb,'aucun',true,'expert','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:117','HSPU ventre au mur','Reverse Wall HS Push-ups','push','push','epaules','["epaules", "triceps"]'::jsonb,'mur',false,'avance','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:118','HSPU libre','Free Handstand Push-ups','push','push','epaules','["epaules", "triceps"]'::jsonb,'aucun',true,'expert','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:120','Front lever groupé avancé','Advanced Tuck Front Lever','pull','pull','dos','["dos", "abdos"]'::jsonb,'barre_traction',false,'intermediaire','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:121','Front lever écarté','Straddle Front Lever','pull','pull','dos','["dos", "abdos"]'::jsonb,'barre_traction',false,'avance','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:122','Front lever complet','Full Front Lever','pull','pull','dos','["dos", "abdos"]'::jsonb,'barre_traction',false,'expert','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:123','Front lever raises','Front Lever Raises','pull','pull','dos','["dos", "abdos"]'::jsonb,'barre_traction',false,'avance','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:124','Back lever groupé','Tuck Back Lever','pull','pull','dos','["dos", "epaules", "biceps"]'::jsonb,'barre_traction',false,'intermediaire','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:125','Back lever une jambe','One Leg Back Lever','pull','pull','dos','["dos", "epaules"]'::jsonb,'barre_traction',false,'intermediaire','temps','skill_statique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:126','Back lever écarté','Straddle Back Lever','pull','pull','dos','["dos", "epaules"]'::jsonb,'barre_traction',false,'avance','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:127','Back lever complet','Full Back Lever','pull','pull','dos','["dos", "epaules"]'::jsonb,'barre_traction',false,'expert','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:128','Back lever drops','Back Lever Drops','pull','pull','dos','["dos", "epaules"]'::jsonb,'barre_traction',false,'avance','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:129','Vertical down hold','Vertical Down Hold','pull','pull','epaules','["epaules", "obliques", "dos"]'::jsonb,'barre_traction',false,'intermediaire','temps','skill_statique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:130','Vertical up hold','Vertical Up Hold','pull','pull','epaules','["epaules", "obliques"]'::jsonb,'barre_traction',false,'intermediaire','temps','skill_statique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:131','Human flag groupé','Tucked Human Flag','pull','pull','epaules','["epaules", "obliques", "dos"]'::jsonb,'barre_traction',false,'avance','temps','skill_statique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:132','Human flag une jambe','One Leg Human Flag','pull','pull','epaules','["epaules", "obliques"]'::jsonb,'barre_traction',false,'avance','temps','skill_statique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:133','Human flag complet','Full Human Flag','pull','pull','epaules','["epaules", "obliques", "dos"]'::jsonb,'barre_traction',false,'expert','temps','skill_statique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:134','Elbow planche','Elbow Planche','push','push','epaules','["epaules", "abdos"]'::jsonb,'aucun',true,'intermediaire','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:135','Planche groupée','Tuck Planche','push','push','epaules','["epaules", "abdos"]'::jsonb,'barres_paralleles',false,'avance','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:136','Planche écartée','Straddle Planche','push','push','epaules','["epaules", "abdos"]'::jsonb,'barres_paralleles',false,'expert','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:137','Planche complète','Full Planche','push','push','epaules','["epaules", "abdos"]'::jsonb,'barres_paralleles',false,'expert','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:138','Tractions explosives','Explosive Pull-ups','pull','pull','dos','["dos", "biceps"]'::jsonb,'barre_traction',false,'intermediaire','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:139','Muscle up avec élan','Kipping Muscle Up','pull','pull','dos','["dos", "pectoraux", "triceps"]'::jsonb,'barre_traction',false,'avance','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:140','Muscle up strict','Strict Muscle Up','pull','pull','dos','["dos", "pectoraux", "triceps"]'::jsonb,'barre_traction',false,'expert','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:141','Muscle up aux anneaux','Ring Muscle Up','pull','pull','dos','["dos", "pectoraux", "triceps"]'::jsonb,'anneaux',false,'expert','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:142','360 muscle up','360 Muscle Up','pull','pull','dos','["dos", "corps_entier"]'::jsonb,'barre_traction',false,'expert','reps','freestyle',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:143','Shrimp flip','Shrimp Flip','pull','pull','corps_entier','["corps_entier"]'::jsonb,'barre_traction',false,'expert','reps','freestyle',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:144','Switchblade','Switchblade','pull','pull','corps_entier','["corps_entier"]'::jsonb,'barre_traction',false,'expert','reps','freestyle',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:145','Impossible dip','Impossible Dip','push','push','triceps','["triceps", "pectoraux", "epaules"]'::jsonb,'barres_paralleles',false,'expert','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:146','Pompes inclinées','Incline Push-ups','push','push','pectoraux','["pectoraux", "triceps"]'::jsonb,'chaise_banc',false,'debutant','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:147','Pompes claquées','Clap Push-ups','push','push','pectoraux','["pectoraux", "triceps"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:148','Pompes tigerbend','Tigerbend Push-ups','push','push','triceps','["triceps", "epaules"]'::jsonb,'aucun',true,'avance','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:149','Pompes aux anneaux','Ring Push-ups','push','push','pectoraux','["pectoraux", "abdos"]'::jsonb,'anneaux',false,'intermediaire','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:150','Pompes profondes aux anneaux','Deep Ring Push-ups','push','push','pectoraux','["pectoraux"]'::jsonb,'anneaux',false,'avance','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:151','Tenue basse de pompe','Push-up Hold','push','push','pectoraux','["pectoraux", "abdos"]'::jsonb,'aucun',true,'debutant','temps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:152','Dips à la barre droite','Straight Bar Dips','push','push','pectoraux','["pectoraux", "triceps"]'::jsonb,'barre_traction',false,'intermediaire','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:153','Dips profonds barre droite','Deep Straight Bar Dips','push','push','pectoraux','["pectoraux", "triceps"]'::jsonb,'barre_traction',false,'avance','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:154','Dips profonds aux anneaux','Deep Ring Dips','push','push','pectoraux','["pectoraux", "triceps"]'::jsonb,'anneaux',false,'avance','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:155','Russian dips','Russian Dips','push','push','triceps','["triceps"]'::jsonb,'barres_paralleles',false,'avance','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:156','Dips lestés','Weighted Dips','push','push','pectoraux','["pectoraux", "triceps"]'::jsonb,'barres_paralleles',false,'avance','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:157','Pompes lestées','Weighted Push-ups','push','push','pectoraux','["pectoraux", "triceps"]'::jsonb,'aucun',true,'intermediaire','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:158','Tractions prise large','Wide Grip Pull-ups','pull','pull','dos','["dos"]'::jsonb,'barre_traction',false,'intermediaire','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:159','Tractions aux anneaux','Ring Pull-ups','pull','pull','dos','["dos", "biceps"]'::jsonb,'anneaux',false,'intermediaire','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:160','Rowing australien aux anneaux','Australian Ring Pull-ups','pull','pull','dos','["dos", "biceps"]'::jsonb,'anneaux',false,'debutant','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:161','Tractions typewriter','Typewriter Pull-ups','pull','pull','dos','["dos", "biceps"]'::jsonb,'barre_traction',false,'expert','reps','skill_dynamique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:162','Tractions lestées','Weighted Pull-ups','pull','pull','dos','["dos", "biceps"]'::jsonb,'barre_traction',false,'avance','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:163','Tenue haute de traction','Pull-up Hold','pull','pull','dos','["dos", "biceps"]'::jsonb,'barre_traction',false,'debutant','temps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:164','Pelican curls','Pelican Curls','pull','pull','biceps','["biceps", "pectoraux"]'::jsonb,'anneaux',false,'avance','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:165','Box jumps','Box Jumps','jambes','jambes','quadriceps','["quadriceps", "fessiers", "mollets"]'::jsonb,'chaise_banc',false,'intermediaire','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:166','Fentes marchées','Walking Lunges','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:167','Squats profonds','Deep Squats','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'aucun',true,'debutant','reps','basique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:168','Pistol squat assisté','Assisted Pistol Squat','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'aucun',true,'debutant','reps','basique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:169','Pistol squat barre basse','Low Bar Pistol Squat','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'barre_traction',false,'avance','reps','basique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:170','Pistol squat barre haute','High Bar Pistol Squat','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'barre_traction',false,'expert','reps','basique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:171','Pistol squat lesté','Weighted Pistol Squat','jambes','jambes','quadriceps','["quadriceps", "fessiers"]'::jsonb,'aucun',true,'avance','reps','basique',true,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:172','Hollow body hold','Hollow Body Hold','core','core','abdos','["abdos"]'::jsonb,'aucun',true,'debutant','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:173','Superman hold','Superman Hold','core','core','lombaires','["lombaires", "fessiers"]'::jsonb,'aucun',true,'debutant','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:174','L-sit suspendu','Hanging L-sit','core','core','abdos','["abdos", "flechisseurs_hanche"]'::jsonb,'barre_traction',false,'intermediaire','temps','skill_statique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:175','Dragon fly','Dragon Fly','core','core','abdos','["abdos", "lombaires"]'::jsonb,'chaise_banc',false,'avance','reps','skill_dynamique',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:176','Pont / extension dorsale','Back Bending / Bridge','mobilite','mobilite','dos','["dos", "epaules", "abdos"]'::jsonb,'aucun',true,'intermediaire','temps','mobilite',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:177','Mobilité d''épaules (dislocates)','Shoulder Mobility / Dislocates','mobilite','mobilite','epaules','["epaules"]'::jsonb,'aucun',true,'debutant','reps','mobilite',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)'),
('cal:178','Mobilité de poignets','Wrist Mobility Routine','mobilite','mobilite','avant_bras','["avant_bras", "poignets"]'::jsonb,'aucun',true,'debutant','temps','mobilite',false,true,'calisthenics_family_guide','Calisthénie — source : Calisthenics Training Guide – Calisthenics Family (noms d''exercices uniquement)')
) as v(ref,name,name_en,category,muscle_group,target_muscle,secondary_muscles,equipment,no_equipment,level,measure,exercise_type,unilateral,is_calisthenics,source,attribution)
where not exists (select 1 from public.exercise_library e where e.ref = v.ref);

insert into public.progression_families (key,name,category,source)
values ('handstand','Équilibre sur les mains','skill','calisthenics_family_guide'),
('hspu','Handstand push-up','push','calisthenics_family_guide'),
('front_lever','Front lever','pull','calisthenics_family_guide'),
('back_lever','Back lever','pull','calisthenics_family_guide'),
('human_flag','Drapeau humain','pull','calisthenics_family_guide'),
('planche','Planche','push','calisthenics_family_guide'),
('muscle_up','Muscle up','pull','calisthenics_family_guide'),
('pistol','Pistol squat','jambes','calisthenics_family_guide')
on conflict (key) do nothing;

insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,1,(select id from public.exercise_library where ref='cal:110'),'Frog stand','Frog Stand' from public.progression_families f where f.key='handstand' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=1);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,2,(select id from public.exercise_library where ref='cal:111'),'ATR dos au mur','Wall Handstand (back to wall)' from public.progression_families f where f.key='handstand' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=2);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,3,(select id from public.exercise_library where ref='cal:112'),'ATR ventre au mur','Reverse Wall Handstand' from public.progression_families f where f.key='handstand' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=3);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,4,(select id from public.exercise_library where ref='cal:113'),'ATR libre','Freestanding Handstand' from public.progression_families f where f.key='handstand' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=4);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,5,(select id from public.exercise_library where ref='cal:114'),'L-sit to handstand','L-sit to Handstand' from public.progression_families f where f.key='handstand' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=5);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,6,(select id from public.exercise_library where ref='cal:115'),'Press to handstand','Press to Handstand' from public.progression_families f where f.key='handstand' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=6);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,1,(select id from public.exercise_library where ref='cal:22'),'Pompes piquées','Pike Push-ups' from public.progression_families f where f.key='hspu' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=1);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,2,(select id from public.exercise_library where ref='cal:27'),'HSPU au mur','Wall Handstand Push-ups' from public.progression_families f where f.key='hspu' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=2);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,3,(select id from public.exercise_library where ref='cal:117'),'HSPU ventre au mur','Reverse Wall HS Push-ups' from public.progression_families f where f.key='hspu' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=3);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,4,(select id from public.exercise_library where ref='cal:118'),'HSPU libre','Free Handstand Push-ups' from public.progression_families f where f.key='hspu' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=4);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,1,(select id from public.exercise_library where ref='cal:10'),'Front lever groupé','Tuck Front Lever' from public.progression_families f where f.key='front_lever' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=1);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,2,(select id from public.exercise_library where ref='cal:120'),'Front lever groupé avancé','Advanced Tuck Front Lever' from public.progression_families f where f.key='front_lever' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=2);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,3,(select id from public.exercise_library where ref='cal:121'),'Front lever écarté','Straddle Front Lever' from public.progression_families f where f.key='front_lever' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=3);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,4,(select id from public.exercise_library where ref='cal:122'),'Front lever complet','Full Front Lever' from public.progression_families f where f.key='front_lever' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=4);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,1,(select id from public.exercise_library where ref='cal:124'),'Back lever groupé','Tuck Back Lever' from public.progression_families f where f.key='back_lever' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=1);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,2,(select id from public.exercise_library where ref='cal:125'),'Back lever une jambe','One Leg Back Lever' from public.progression_families f where f.key='back_lever' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=2);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,3,(select id from public.exercise_library where ref='cal:126'),'Back lever écarté','Straddle Back Lever' from public.progression_families f where f.key='back_lever' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=3);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,4,(select id from public.exercise_library where ref='cal:127'),'Back lever complet','Full Back Lever' from public.progression_families f where f.key='back_lever' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=4);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,1,(select id from public.exercise_library where ref='cal:129'),'Vertical down hold','Vertical Down Hold' from public.progression_families f where f.key='human_flag' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=1);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,2,(select id from public.exercise_library where ref='cal:130'),'Vertical up hold','Vertical Up Hold' from public.progression_families f where f.key='human_flag' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=2);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,3,(select id from public.exercise_library where ref='cal:131'),'Human flag groupé','Tucked Human Flag' from public.progression_families f where f.key='human_flag' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=3);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,4,(select id from public.exercise_library where ref='cal:132'),'Human flag une jambe','One Leg Human Flag' from public.progression_families f where f.key='human_flag' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=4);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,5,(select id from public.exercise_library where ref='cal:133'),'Human flag complet','Full Human Flag' from public.progression_families f where f.key='human_flag' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=5);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,1,(select id from public.exercise_library where ref='cal:26'),'Pompes pseudo planche','Pseudo Planche Push-ups' from public.progression_families f where f.key='planche' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=1);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,2,(select id from public.exercise_library where ref='cal:134'),'Elbow planche','Elbow Planche' from public.progression_families f where f.key='planche' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=2);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,3,(select id from public.exercise_library where ref='cal:135'),'Planche groupée','Tuck Planche' from public.progression_families f where f.key='planche' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=3);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,4,(select id from public.exercise_library where ref='cal:136'),'Planche écartée','Straddle Planche' from public.progression_families f where f.key='planche' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=4);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,5,(select id from public.exercise_library where ref='cal:137'),'Planche complète','Full Planche' from public.progression_families f where f.key='planche' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=5);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,1,(select id from public.exercise_library where ref='cal:138'),'Tractions explosives','Explosive Pull-ups' from public.progression_families f where f.key='muscle_up' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=1);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,2,(select id from public.exercise_library where ref='cal:139'),'Muscle up avec élan','Kipping Muscle Up' from public.progression_families f where f.key='muscle_up' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=2);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,3,(select id from public.exercise_library where ref='cal:140'),'Muscle up strict','Strict Muscle Up' from public.progression_families f where f.key='muscle_up' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=3);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,4,(select id from public.exercise_library where ref='cal:141'),'Muscle up aux anneaux','Ring Muscle Up' from public.progression_families f where f.key='muscle_up' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=4);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,1,(select id from public.exercise_library where ref='cal:168'),'Pistol squat assisté','Assisted Pistol Squat' from public.progression_families f where f.key='pistol' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=1);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,2,(select id from public.exercise_library where ref='cal:39'),'Pistol squats','Pistol Squats' from public.progression_families f where f.key='pistol' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=2);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,3,(select id from public.exercise_library where ref='cal:169'),'Pistol squat barre basse','Low Bar Pistol Squat' from public.progression_families f where f.key='pistol' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=3);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,4,(select id from public.exercise_library where ref='cal:170'),'Pistol squat barre haute','High Bar Pistol Squat' from public.progression_families f where f.key='pistol' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=4);
insert into public.progression_steps (family_id,position,exercise_id,label,name_en) select f.id,5,(select id from public.exercise_library where ref='cal:171'),'Pistol squat lesté','Weighted Pistol Squat' from public.progression_families f where f.key='pistol' and not exists (select 1 from public.progression_steps s where s.family_id=f.id and s.position=5);

insert into public.knowledge_notes (club_id,theme,slug,title,body,origin,source,shareable,status,tags) select null,'ce_qu_est_la_calisth_nie','ce_qu_est_la_calisth_nie','Ce qu''est la calisthénie',$md$Le mot vient du grec *kallos* (beauté) et *sthenos* (force) : littéralement, « la belle force ». Concrètement, c'est l'entraînement de force qui utilise le poids du corps comme seule charge. On y distingue trois familles de pratique :

**Les basiques.** Traction, pompe, dip, squat, gainage. Ce sont les mouvements qui construisent la masse musculaire et la force générale. Ils restent le socle du travail quel que soit le niveau — un pratiquant avancé ne les abandonne jamais, il les rend plus difficiles.

**Les skills (figures).** Des positions tenues à un angle donné contre la gravité : équilibre sur les mains, front lever, back lever, drapeau humain, planche. On parle de *statiques* ou de figures « bras tendus ». Certaines figures sont au contraire *dynamiques* : le muscle up, le handstand push-up, le passage du L-sit à l'équilibre.

**Le freestyle.** L'enchaînement libre de figures explosives et de statiques, sur lequel reposent la plupart des compétitions. C'est un aboutissement, pas un point de départ.

Ces trois familles ne s'opposent pas : les basiques nourrissent les skills, et les skills rendent les basiques plus faciles.$md$,'calisthenics_dataset','Guide de calisthénie (contenu original — voir datasets/calisthenie_complet.json)',false,'published',array['calisthenie','guide'] where not exists (select 1 from public.knowledge_notes k where k.origin='calisthenics_dataset' and k.slug='ce_qu_est_la_calisth_nie');
insert into public.knowledge_notes (club_id,theme,slug,title,body,origin,source,shareable,status,tags) select null,'les_quatre_qualit_s_d_velopper','les_quatre_qualit_s_d_velopper','Les quatre qualités à développer',$md$Un pratiquant qui progresse durablement travaille quatre choses en parallèle.

| Qualité | Ce que c'est | Comment on l'entraîne |
|---|---|---|
| **Force** | Produire de la tension avec les bras fléchis, en mouvement | Tractions, dips, pompes, HSPU, muscle up |
| **Skills** | Tenir une position bras tendus contre la gravité | Statiques, progressions par paliers |
| **Souplesse** | Longueur des muscles | Étirements en flexion avant, en extension dorsale, ischios, épaules |
| **Mobilité** | Amplitude de mouvement des articulations | Mobilité d'épaules, de poignets, de hanches |

La confusion la plus fréquente porte sur les deux dernières : la **souplesse** dépend des muscles, la **mobilité** de l'articulation elle-même. Un ATR bien aligné demande de la souplesse d'épaules ; un *skin the cat* demande de la mobilité de l'épaule. Les deux se travaillent différemment.

Ces qualités se renforcent mutuellement. Progresser à l'équilibre aide la planche. Devenir fort en dips aide les handstand push-ups. Gagner en souplesse d'ischios rend le back lever plus droit.$md$,'calisthenics_dataset','Guide de calisthénie (contenu original — voir datasets/calisthenie_complet.json)',false,'published',array['calisthenie','guide'] where not exists (select 1 from public.knowledge_notes k where k.origin='calisthenics_dataset' and k.slug='les_quatre_qualit_s_d_velopper');
insert into public.knowledge_notes (club_id,theme,slug,title,body,origin,source,shareable,status,tags) select null,'les_principes_d_entra_nement','les_principes_d_entra_nement','Les principes d''entraînement',$md$Ce sont les règles d'adaptation du corps. Elles ne sont pas propres à la calisthénie, mais elles s'y appliquent avec une force particulière.

**Régularité.** Les résultats se comptent en mois et en années, pas en semaines. Une figure comme l'ATR aligné ou la planche demande souvent plus d'un an. Les coupures longues et répétées sont ce qui empêche le plus de gens de progresser.

**Fréquence.** Pour apprendre un geste, la répétition fréquente compte plus que la durée d'une séance. Mieux vaut travailler l'équilibre 20 minutes quatre fois par semaine qu'une heure le dimanche. C'est un apprentissage moteur autant qu'un travail de force.

**Objectifs limités.** Deux à trois skills maximum sur un cycle donné, plus quelques exercices de force. Vouloir tout travailler en même temps, c'est avancer d'un centimètre partout.

**Spécificité.** Le corps s'adapte dans la direction où on le charge. Renforcer son gainage ne donne pas un back lever : il faut pratiquer le back lever lui-même, et l'entourer d'exercices qui le servent.

**Surcharge progressive.** Chaque cycle doit demander un peu plus que le précédent : une seconde de plus, une répétition de plus, un levier plus long, une amplitude plus grande. Sans augmentation de la contrainte, il n'y a pas de raison de s'adapter.

**Paliers.** Ne cherche pas à étirer une même variante à l'infini. Si tu tiens 20 secondes de front lever groupé, passe à la variante suivante plutôt que de viser 60 secondes. Le nouveau stimulus fait plus progresser que la durée.

**Rendement décroissant.** Les premiers progrès sont rapides, puis ils ralentissent jusqu'au plateau. C'est normal. On le contourne en changeant de stimulus : nouvelle variante, nouvel angle, nouveau format. Travailler par blocs de 8 à 12 semaines permet d'anticiper ce moment.

**Réversibilité.** Ce qui se construit se perd à peu près aussi vite. La force et les skills se dégradent plus vite que la souplesse et la mobilité. Une semaine de coupure après deux mois de travail est bénéfique ; au-delà de deux semaines sans raison, on recule.

**Suivi.** Note tes résultats. Un carnet ou l'historique de l'app suffit : tu commences chaque séance en sachant précisément quel chiffre battre. C'est le mécanisme le plus simple pour appliquer la surcharge progressive sans y penser.$md$,'calisthenics_dataset','Guide de calisthénie (contenu original — voir datasets/calisthenie_complet.json)',false,'published',array['calisthenie','guide'] where not exists (select 1 from public.knowledge_notes k where k.origin='calisthenics_dataset' and k.slug='les_principes_d_entra_nement');
insert into public.knowledge_notes (club_id,theme,slug,title,body,origin,source,shareable,status,tags) select null,'construire_une_s_ance','construire_une_s_ance','Construire une séance',$md$**Échauffement (8-10 min).** Élévation cardiaque, puis mobilité ciblée sur les articulations sollicitées — poignets et épaules avant toute séance de poussée ou d'ATR, hanches avant les jambes. Termine par des séries légères du premier exercice.

**Ordre des exercices.** Du plus exigeant au moins exigeant sur le plan nerveux :
1. Skills et statiques (à faire frais, jamais en fin de séance)
2. Force lourde en poussée et en tirage
3. Volume d'assistance
4. Gainage
5. Étirements ou retour au calme

**Séries, répétitions, repos.**

| Objectif | Format | Repos |
|---|---|---|
| Skill / statique | 4-6 séries de 10-30 s, loin de l'échec | 90-150 s |
| Force max | 4-6 séries de 3-6 reps | 2-3 min |
| Hypertrophie | 3-4 séries de 8-15 reps | 60-90 s |
| Endurance / circuit | 3-5 tours, 30-60 s par exercice | 15-30 s entre exercices |

**Règle des statiques :** la série s'arrête quand la position se dégrade, pas quand tu tombes. Une tenue de 12 secondes propre vaut mieux qu'une de 20 secondes cassée — c'est la position propre que le corps apprend.$md$,'calisthenics_dataset','Guide de calisthénie (contenu original — voir datasets/calisthenie_complet.json)',false,'published',array['calisthenie','guide'] where not exists (select 1 from public.knowledge_notes k where k.origin='calisthenics_dataset' and k.slug='construire_une_s_ance');
insert into public.knowledge_notes (club_id,theme,slug,title,body,origin,source,shareable,status,tags) select null,'mod_les_de_semaine','mod_les_de_semaine','Modèles de semaine',$md$Quatre organisations, du plus simple au plus spécialisé. Elles sont détaillées dans le fichier de séances.

**Débutant — 3 jours full body.** Le corps entier trois fois par semaine, un jour sur deux. C'est le format le plus efficace quand on part de zéro : fréquence élevée sur chaque mouvement, récupération suffisante.

**Push / Pull / Jambes.** Poussée, tirage, jambes, plus un jour de gainage et un jour de cardio. Simple à organiser, mais la frontière poussée/tirage est artificielle en calisthénie : un muscle up sollicite le dos, les épaules et les bras dans le même mouvement.

**Haut / Bas.** Alterne haut et bas du corps. Utile pour rééquilibrer un déséquilibre entre les deux, ou quand on veut cinq séances par semaine sans surcharger le haut du corps.

**Skill / Force en alternance.** L'organisation la plus adaptée dès qu'on vise des figures : un jour bras tendus (statiques), un jour bras fléchis (force dynamique), séparés par de la récupération active. Chaque type revient deux fois par semaine, et comme les deux se nourrissent mutuellement, la figure visée est indirectement travaillée quatre fois.

**En complément — la pratique quotidienne.** Une ou plusieurs mini-sessions par jour d'un même exercice, toujours très loin de l'échec (50-60 % du max). Idéal pour l'ATR ou les tenues de gainage. Ça ne remplace pas un programme, ça s'y ajoute.

**En complément — le circuit.** Enchaîner les exercices sans pause. Format à privilégier quand le temps manque ou en déplacement. Varie les angles et mélange dynamique et statique dans un même circuit.$md$,'calisthenics_dataset','Guide de calisthénie (contenu original — voir datasets/calisthenie_complet.json)',false,'published',array['calisthenie','guide'] where not exists (select 1 from public.knowledge_notes k where k.origin='calisthenics_dataset' and k.slug='mod_les_de_semaine');
insert into public.knowledge_notes (club_id,theme,slug,title,body,origin,source,shareable,status,tags) select null,'progresser_sur_une_figure','progresser_sur_une_figure','Progresser sur une figure',$md$Chaque figure se décompose en paliers, du plus court levier au plus long. Le principe est toujours le même : plus le corps est ramassé, plus la figure est facile ; plus il s'allonge, plus le bras de levier augmente.

- **Équilibre sur les mains** : frog stand → dos au mur → ventre au mur → équilibre libre → entrées en force
- **Front lever** : groupé → groupé avancé → écarté → complet
- **Back lever** : groupé → une jambe → écarté → complet
- **Drapeau humain** : tenue verticale tête en bas → tenue verticale tête en haut → groupé → une jambe → complet
- **Planche** : elbow planche → groupée → écartée → complète
- **Muscle up** : tractions explosives → avec élan → strict → aux anneaux
- **Handstand push-up** : pompes piquées → au mur → ventre au mur → libre
- **Pistol squat** : assisté → complet → barre basse → barre haute → lesté

Ne passe au palier suivant que lorsque le palier actuel est solide et propre — une tenue de 15-20 secondes maîtrisée est un bon repère.$md$,'calisthenics_dataset','Guide de calisthénie (contenu original — voir datasets/calisthenie_complet.json)',false,'published',array['calisthenie','guide'] where not exists (select 1 from public.knowledge_notes k where k.origin='calisthenics_dataset' and k.slug='progresser_sur_une_figure');
insert into public.knowledge_notes (club_id,theme,slug,title,body,origin,source,shareable,status,tags) select null,'r_cup_ration_alimentation_hydratation','r_cup_ration_alimentation_hydratation','Récupération, alimentation, hydratation',$md$**Récupération.** 48 h entre deux sollicitations lourdes du même groupe. En calisthénie, presque tous les exercices engagent épaules, dos, bras et gainage : les jours de repos ne sont pas optionnels. Le sommeil reste le levier de récupération le plus puissant.

**Poids de corps.** En calisthénie, la charge à déplacer, c'est toi. Un rapport force/poids favorable rend mécaniquement les figures plus accessibles. Cela ne veut pas dire chercher la maigreur : la masse musculaire est ce qui produit la force. L'approche raisonnable est de manger suffisamment pour soutenir l'entraînement et la construction musculaire, sans excédent important et prolongé.

**Protéines.** Les recommandations pour les sportifs de force se situent autour de 1,6 à 2,2 g par kilo de poids de corps et par jour, répartis sur la journée. Sources : viande, poisson, œufs, produits laitiers, légumineuses, tofu, céréales complètes, oléagineux.

**Glucides.** La principale source d'énergie à l'effort. Privilégie les glucides complexes (riz, pâtes complètes, flocons d'avoine, pommes de terre, légumineuses) autour des séances, plutôt que les sucres rapides.

**Lipides.** Environ 20 à 35 % des apports quotidiens, en privilégiant les graisses insaturées (huiles végétales, oléagineux, poissons gras).

**Hydratation.** 1,5 à 2 L par jour en base, davantage à l'entraînement : compte environ 1 L supplémentaire par heure d'effort intense.

**Compléments.** Ils complètent une alimentation variée, ils ne la remplacent pas. La vitamine D est le supplément le plus souvent justifié sous nos latitudes en hiver.

> Ces repères sont d'ordre général. Pour un besoin individuel — pathologie, régime particulier, perte ou prise de poids importante — l'avis d'un médecin ou d'un diététicien reste indispensable.$md$,'calisthenics_dataset','Guide de calisthénie (contenu original — voir datasets/calisthenie_complet.json)',false,'published',array['calisthenie','guide'] where not exists (select 1 from public.knowledge_notes k where k.origin='calisthenics_dataset' and k.slug='r_cup_ration_alimentation_hydratation');
insert into public.knowledge_notes (club_id,theme,slug,title,body,origin,source,shareable,status,tags) select null,'s_curit','s_curit','Sécurité',$md$- Fais examiner par un professionnel de santé toute douleur articulaire qui persiste : épaules, coudes et poignets sont les zones les plus exposées en calisthénie.
- Échauffe systématiquement les poignets avant tout appui au sol ou aux barres.
- Ne travaille jamais une statique jusqu'à la chute : les sorties de position non contrôlées sont la première cause de blessure.
- Apprends l'ATR près d'un mur ou avec une sortie en roulade avant de tenter le libre.
- Le lest (tractions, dips, pompes lestées) vient après la maîtrise du mouvement au poids du corps, pas avant.
- En cas de doute sur ton aptitude à l'effort, consulte un médecin avant de commencer.

---

*Ce guide est un contenu original rédigé pour accompagner la bibliothèque d'exercices de l'application. Il n'est ni une reproduction ni une traduction d'un ouvrage existant.*$md$,'calisthenics_dataset','Guide de calisthénie (contenu original — voir datasets/calisthenie_complet.json)',false,'published',array['calisthenie','guide'] where not exists (select 1 from public.knowledge_notes k where k.origin='calisthenics_dataset' and k.slug='s_curit');
